### ISSUE TITLE
vs addon fail

### ISSUE THREAD

**Issue by brunis** [madskristensen/WebCompiler#153]
The compile on save is working, but not properly stamping the file changed, which is probably why the BundlerMinifier is not kicking in.

**Comment by brunis** [comment]
even if i delete the generated file you recreate it with the last timestamp, which in this case was yesterday..

**Comment by alfredoceballosr** [comment]
This issue on Web compiler extension is pretty important since if the file change time is not updated, other tools like Bundler & Minifier extension that relay on this change will not be triggered.

A very simple scenario to reproduce the issue is to create a SCSS file and compile it into a CSS. Then bundle the resulting CSS file with other style sheets at hand. You'll notice that when you update and save the SCSS file, the compiled CSS works fine and reflects the changes, but the bundled and minified file is never updated.

**Comment by madskristensen** [comment]
This extension does not timestampt the compiled files. It simply just writes them to disk with this code:

```c#
File.WriteAllText(fileName, content, new UTF8Encoding(true));
```

The fix lies with the Bundler & Minifier extension and not this one. You already opened a ticket to track it here https://github.com/madskristensen/BundlerMinifier/issues/86
