### ISSUE TITLE
Saving SCSS partials does not trigger main file to compile

### ISSUE THREAD

**Issue by angeliquejw** [madskristensen/WebCompiler#191]
I am using a SMACSS-inspired organization for my files, where I have a main `styles.scss` file that imports partials, some of which are in folders, e.g.

`@import 'variables', 'base', 'layout/layout', 'modules/modules', 'theme/theme', 'states';`

In an earlier version of WebCompiler, when I would save `_base.scss` or any other partial, `styles.scss` would automatically recompile, and I would see the changes in my browser. This no longer works for me as of Web Compiler v 1.10.302 and/or v 1.10.303.

I have attempted deleting my project's `compilerconfig.json` and starting a new file and today uninstalled and reinstalled the WebCompiler plugin, all to no avail.

I am running Visual Studio Professional 2015 v 14.0.24720.00 Update 1 and my current `compilerconfig.json` looks like this:

`[
  {
    "outputFile": "Styles/styles.css",
    "inputFile": "Styles/styles.scss"
  }
]`

`compilerconfig.json.defaults':

`{
  "compilers": {
    "less": {
      "autoPrefix": "",
      "cssComb": "none",
      "ieCompat": true,
      "strictMath": false,
      "strictUnits": false,
      "relativeUrls": true,
      "rootPath": "",
      "sourceMapRoot": "",
      "sourceMapBasePath": "",
      "sourceMap": false
    },
    "sass": {
      "includePath": "",
      "indentType": "space",
      "indentWidth": 2,
      "outputStyle": "nested",
      "Precision": 5,
      "relativeUrls": true,
      "sourceMapRoot": "",
      "sourceMap": false
    },
    "stylus": {
      "sourceMap": false
    },
    "babel": {
      "sourceMap": false
    },
    "coffeescript": {
      "bare": false,
      "runtimeMode": "node",
      "sourceMap": false
    }
  },
  "minifiers": {
    "css": {
      "enabled": true,
      "termSemicolons": true,
      "gzip": false
    },
    "javascript": {
      "enabled": true,
      "termSemicolons": true,
      "gzip": false
    }
  }
}`

**Comment by madskristensen** [comment]
@angeliquejw thanks for the bug report. Can you help test if this is fixed by downloading the latest CI build from http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/ ?

**Comment by angeliquejw** [comment]
Grabbed, installed and working like a dream. Thank you so much, @madskristensen. I honestly want to send you flowers, coffee and generally throw you a ticker tape parade. This had been driving me batty.

**Comment by madskristensen** [comment]
Awesome. Glad it worked

**Comment by Dmasci99** [comment]
Hi @madskristensen  , 

The link provided in 2016 has since been removed. 

Is there any other accounts of this occurring? This has been happening to me periodically and the only workaround available is to re-create all .scss files manually. Any time I try to copy the files from a different project it seems to break whatever automatic compilation exists in the child-parent relationship. 

This workaround is becoming extremely exhausting and unreliable due to the growing size of my work. 

PS: My issue is the same as described. My parent "Master.scss" file will not force a re-compile when any imported .scss files receive a change in Visual Studio. Saving the "Master.scss" file manually re-compiles the .css file successfully.
Note: I get the "Compiled Successfully" message; however, the .css file remains unchanged. All files are confirmed as **not** read-only.

Editor: Visual Studio 2019 (16.9.3)
Web Compiler Version: 1.12.394
