### ISSUE TITLE
a problem with the sass compiler that is used

### ISSUE THREAD

**Issue by Joshlo** [madskristensen/WebCompiler#24]
Hi Mads,

First of all, I love this extension!

But there seems to be a problem when I try to compile the following Sass,

I have a list looking somthing like this:
```
$mdi-list-icons: ('navigation-menu': '\e8a1', ...);
```
And my loop through the list looks like this:
```
@each $mdi-icon-name, $mdi-icon-value in $mdi-list-icons {
  .#{$mdi-prefix}#{$mdi-icon-name}:before {
    content: $mdi-icon-value;
  }
}
```
the problem is, that the result looks like this: (which the font can't interpret)
```
.mdi-navigation-menu:before {
  content: 'î¢¡'; }
```
Where it should look like this:
```
.mdi-navigation-menu:before {
  content: '\e8a1'; }
```
The sass file is from: http://materializecss.com/

And they write that this bug should have been fixed in Sass v. 3.3.x. is it possible to update it?
Because their fix gives the same error

**Comment by am11** [comment]
Hello @Joshlo, this extension is using @darrenkopp's libsass-net library as dependency: https://github.com/darrenkopp/libsass-net, which is the wrapper around libsass. The current version of [libsass is v3.2.5](https://github.com/sass/libsass/releases/tag/3.2.5), while libsass-net's latest master is consuming v3.2.4 https://github.com/darrenkopp/libsass-net/blob/master/README.md.

When someone says Sass compiler, it usually considered as ruby-sass. While libsass is alternative implementation of ruby-sass and is written in C++ (instead of Ruby) and hence is blazingly fast in comparison; it is still yet to fully conform with Sass language v3.4, but they are very very near to level the gap, as reflected by the checklist at https://github.com/sass/libsass/issues/629.

To compare the languages feature among two compilers, you can always use http://sassmeister.com/, where you can click on Settings icon in navbar and switch the compiler (ruby-sass / libsass). 
If you find any disparity in trans-compilation, you can create a gist for an [SSCCE](http://sscce.org/) (on sassmeister, you can click on GitHub icon in top navbar and it will create a gist.github.com link directly from there) and report it to libsass issue tracker: https://github.com/sass/node-sass/issues. 
If you discover a libsass feature, which libsass-net is yet to wrap (for instance, custom importers, custom functions etc.), you can open an issue in libsass-net issue tracker https://github.com/darrenkopp/libsass-net/issues, then WebCompiler can provision the upstream functionality.

The equation boils down to:

>
libsass == { upstream of } ==> libsass-net == { upstream of } ==> WebCompiler

As you can see we can not possibly remedy this issue from WebCompiler.
With that said, there seems to be issue with materialize compiling with libsass: https://github.com/Dogfalo/materialize/pull/287. IMHO, you can request materialize folks to make it compatible with LibSass; since materialize is dependent on Compass framework, which provides many auxiliary helpers for ruby-sass. This is a very fair request as many front-end Sass-based frameworks are already conforming with standard language and yet compilable via libsass and vanilla ruby-sass.

Last but not the least, with VS2013 you can use Web Essentials 2013. It packs both engines (ruby and libsass) which can be switched from `Tools > Options > Web Essentials > Sass`. 

Hope this helps in some way. :)

**Comment by madskristensen** [comment]
Just released a new version that has LibSass v3.2.5. Can you please install the update and verify if this has been fixed?

**Comment by philipvr** [comment]
It appears that this is still a problem in LibSass v3.2.5. The updated Web Compiler v1.0.72 does not fix this issue.

**Comment by madskristensen** [comment]
Ok, thanks for verifying. That means that it hasn't been implemented in LibSass yet and the issue should be opened on that repo

**Comment by philipvr** [comment]
Here is the related LibSass bug: https://github.com/sass/libsass/issues/1231
