### ISSUE TITLE
Saving file causes all files to recompile.

### ISSUE THREAD

**Issue by ihaveworms** [madskristensen/WebCompiler#52]
When saving an individual file, I am seeing all my of my less files in the compilerconfig.json being compiled. I have quite a few less files and having it go through all my files seems like an unnecessary waste.

**Comment by xilefius** [comment]
I have no solution, but the same problem with my 200 coffee files. I have to wait a minute until my changes are visible in the generated js file when I save a coffee file. This does not seem very useful.

On the other hand, we have many scss file that are all included in one "main.scss" so that we only get one large css file. We have not included the small scss files in the compilerconfiguration file, but our main.scss gets compiled whenever we save another scss. This is the desired behavior in this case (for scss files, but not coffee files)

**Comment by xilefius** [comment]
That was fast. Thanks for the fix :-)
